float32 Object_VrelLong
float32 Object_VrelLat
float32 Object_RCS
float32 Object_ID
float32 Object_DynProp
float32 Object_DistLong
float32 Object_DistLat

 float32 Obj_VrelLong_rms 
 float32 Obj_VrelLat_rms 
 float32 Obj_ProbOfExist 
 float32 Obj_Orientation_rms 
 float32 Obj_MeasState 
 float32 Obj_ID2 
 float32 Obj_DistLong_rms 
 float32 Obj_DistLat_rms 
 float32 Obj_ArelLong_rms 
 float32 Obj_ArelLat_rms 



 float32 Object_ID3 
 float32 Object_Width 
 float32 Object_OrientationAngel 
 float32 Object_Length 
 float32 Object_Class 
 float32 Object_ArelLong 
 float32 Object_ArelLat 